### ISSUE TITLE
./gradlew fitnesseRun starts monopoly application

### ISSUE THREAD

**Issue by eskape** [xebia/workshop-agile-testing#10]
Hi Arjan,

After your last change I can't start FitNesse anymore with gradle task fitNesseRun.

25becc3 Arjan Molenaar at 18/12/14 16:02 - Run jetty in the foreground, fix unit test

When I uncomment line 72: daemon = true, it seems to work again.

One other note: I think we should put this project into CI or something to run the test and verify all things are still working... So we won't run into these issues when given trainings ;-)

Cheers
Kishen

**Comment by mjvdende** [comment]
I checked out master and it works fine.

```
workshop-agile-testing maarten$ ./gradlew fitnesseRun
:compileJava UP-TO-DATE
:compileScala UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava UP-TO-DATE
:writeFitNesseClasspath UP-TO-DATE
:fitNesseRun
Bootstrapping FitNesse, the fully integrated standalone wiki and acceptance testing framework.
root page: fitnesse.wiki.fs.FileSystemPage at ./FitNesseRoot
logger: none
authenticator: fitnesse.authentication.PromiscuousAuthenticator
page factory: fitnesse.html.template.PageFactory
page theme: bootstrap
Starting FitNesse on port: 8000
> Building 85% > :fitNesseRun
```

now goto localhost:8000 et voila

**Comment by eswets** [comment]
this is normal; Jetty is now running, that's why your build does not complete. This is why i set it to run in daemon mode.

**Comment by mjvdende** [comment]
@eswets yes this is normal is the command was called startMonopoly or something. But now I want fitnesse to start. Command fitnesseRun does not start fitnesse.

**Comment by eskape** [comment]
I understand that the build does not complete, but the gradle task fitNesseRun now starts the monopoly application. That's not normal ;-) (Changed the title of the issue)

```
➜  workshop-agile-testing git:(master) ./gradlew fitnesseRun
:compileJava UP-TO-DATE
:compileScala UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava UP-TO-DATE
> Building 55% > :jettyRun > Running at http://localhost:8080/workshop-agile-testing
```

When I uncomment line 71: daemon = true, then the gradle task fitnesseRun works again

```
➜  workshop-agile-testing git:(master) ./gradlew fitnesseRun
:compileJava UP-TO-DATE
:compileScala UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava UP-TO-DATE
:jettyRun
:writeFitNesseClasspath UP-TO-DATE
:fitNesseRun
Bootstrapping FitNesse, the fully integrated standalone wiki and acceptance testing framework.
root page: fitnesse.wiki.fs.FileSystemPage at ./FitNesseRoot
logger: none
authenticator: fitnesse.authentication.PromiscuousAuthenticator
page factory: fitnesse.html.template.PageFactory
page theme: bootstrap
Starting FitNesse on port: 8000
> Building 77% > :fitNesseRun
```

**Comment by eskape** [comment]
Oeps, clicked the wrong button - Reopening issue

**Comment by eswets** [comment]
@mjvdende thanks for the clarification, and you're right, fitnesse cannot start if jetty runs in the foreground. The fitnesse task depends on the jettyrun task. If the jettyrun task runs in the foreground it becomes blocking, so fitnesse never starts.

**Comment by mjvdende** [comment]
well @eskape commit the fix en let the build be green again!

**Comment by amolenaar** [comment]
I have made a few private changes that allow for starting the SUT on test set-up. We might want to review those…

**Comment by eswets** [comment]
Sounds good, what do you propose?

**Comment by amolenaar** [comment]
Added my proposal in the startwebapp branch.

**Comment by eswets** [comment]
Looks good, just one small point, the game itself is broken. Players keep getting put in jail.

**Comment by amolenaar** [comment]
Okay... that doesn't occur on the master branch?

**Comment by eskape** [comment]
@amolenaar Did something go wrong merging startwebapp to master (11-01-2015)
When I look at your upgrade dep commit for cucumber-libs in the startwebapp, I see version 1.2.0.
But after the merge I see: 1.1.8.

**Comment by eskape** [comment]
Fixed the issue (for now) by removing dependsOn jettyRun from the fitNesse gradle task. 
@amolenaar was there a specific reason for it? what were you trying to improve/solve?
